"""Scaffold a DRAUPNIR API operation with the conventions of SAD 11E.2 applied.

The output starts the application, generates both clients and passes the API
surface contract with no manual edit. `tests/contract/test_skills.py` mounts it
on a real application and drives it, which is the test of whether this skill is
real.

Three shapes, because the shape is the decision that matters: a collection is
cursor paginated and never offset; an item answers 404 as a problem document;
a mutation requires an `Idempotency-Key` and returns 202 rather than holding a
connection open.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Final

REPO_ROOT = Path(__file__).resolve().parents[3]

#: SAD 9.4's vocabulary, as `draupnir.svalinn.roles.Permission` spells it. A
#: name not in this list is a typo, and a typo here is a route that starts and
#: guards nothing recognisable.
PERMISSIONS: Final = (
    "READ",
    "REGISTER_SOURCE",
    "CURATE",
    "SUBMIT_RUN",
    "CANCEL_RUN",
    "DECIDE_GATE",
    "PUBLISH_RELEASE",
    "MANAGE_USERS",
    "MANAGE_PLUGINS",
    "MANAGE_POLICY",
)

SHAPES: Final = ("collection", "item", "mutation")

#: `listRetention`, `getRunLineage`. It is the generated CLI command's name and
#: the generated TypeScript operation's key, so it is lowerCamelCase and stable.
OPERATION_ID = re.compile(r"^[a-z][a-zA-Z0-9]*$")

#: `/retention`, `/corpora/{iso3}/retention`. Leading slash, no trailing one,
#: no version prefix -- `create_app` mounts every router under `/v1`.
PATH = re.compile(r"^(?:/(?:[a-z][a-z0-9-]*|\{[a-z_][a-z0-9_]*\}))+$")

MODULE = re.compile(r"^[a-z][a-z0-9_]*$")

PATH_PARAM = re.compile(r"\{([a-z_][a-z0-9_]*)\}")


class ScaffoldError(ValueError):
    """The arguments would produce an operation that cannot be registered."""


def snake(camel: str) -> str:
    """`listRetention` -> `list_retention`."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", camel).lower()


HEADER = '''\
"""{summary}. SAD 8.1.

Generated by `skills/draupnir-endpoint`.

Every convention here is one that fails somewhere other than this file when it
is missed: a route without `@needs` stops `create_app`, an operation without an
`operation_id` stops the client generator, and a model that is not a `Wire`
answers snake_case to a console that reads camelCase.
"""

from __future__ import annotations

{imports}
router = APIRouter(tags=["{tag}"])
'''

MODELS_COLLECTION = '''

class {model}Out(Wire):
    """One row of the collection.

    Extends `Wire`, which carries the camelCase alias generator and
    `extra="forbid"`. Every field is described, because those descriptions are
    what the generated client's documentation and the console's tooltips are
    made of, and writing them here is what stops them being written twice.
    """

    id: str = Field(description="Stable identifier for this row.")


class {model}Page(Wire):
    """A page of them. Cursor paginated, never offset (AC-B3)."""

    items: list[{model}Out] = Field(description="This page's rows.")
    meta: PageMeta = Field(description="Where the next page starts.")
'''

MODELS_ITEM = '''

class {model}Out(Wire):
    """The resource.

    Extends `Wire`, which carries the camelCase alias generator and
    `extra="forbid"`. Every field is described, because those descriptions are
    what the generated client's documentation and the console's tooltips are
    made of.
    """

    id: str = Field(description="Stable identifier for this resource.")
'''

MODELS_MUTATION = '''

class {model}In(Wire):
    """What the caller sends.

    `extra="forbid"` comes from `Wire`, so a misspelled field is a 422 with a
    problem document rather than a silently ignored value.
    """

    reason: str = Field(description="Why this is being done. Recorded in the ledger.")
'''

READ_NOTE = """
    # The read model has no method for this yet, and an endpoint that invented
    # rows would be worse than one that returns none: `EmptyReadModel` is what
    # a contract test runs against, and answering nothing is its honest answer.
    #
    # To make this return something, add the method to the `ReadModel` Protocol
    # in `draupnir/api/reading.py` and to both implementations. Read through
    # `_scoped()`: row-level security shows zero rows to a session that has not
    # set `draupnir.site_id`, so site scoping is enforced by the database
    # rather than by remembering a WHERE clause (AC-B10, AC-F18).
"""

COLLECTION = '''

@router.get(
    "{path}",
    summary="{summary}",
    operation_id="{operation_id}",
    response_model={model}Page,
)
@needs(Permission.{permission})
async def {function}(
    ctx: Guarded,
    reading: Reading,
    limit: PageSize,
    cursor: Cursor = None,{path_args}
) -> {model}Page:
    """{summary}."""
    del ctx, reading, cursor{path_deletes}
{read_note}
    page = {model}Page(items=[], meta=PageMeta(next_cursor=None, limit=limit))
    telemetry.log("{tag}.listed", count=len(page.items))
    return page
'''

ITEM = '''

@router.get(
    "{path}",
    summary="{summary}",
    operation_id="{operation_id}",
    response_model={model}Out,
)
@needs(Permission.{permission})
async def {function}(
    ctx: Guarded,
    reading: Reading,{path_args}
) -> {model}Out:
    """{summary}.

    A resource that is not there is a problem document with a stable type URI,
    not a bare 404 and never an `HTTPException` (AC-B2).
    """
    del ctx, reading
{read_note}
    raise ProblemError(
        status=404,
        code="{code}-not-found",
        title="Not found",
        detail=f"no {tag} {detail_expression}",
    )
'''

MUTATION = '''

@router.post(
    "{path}",
    summary="{summary}",
    operation_id="{operation_id}",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=Accepted,
)
@needs(Permission.{permission})
async def {function}(
    body: {model}In,
    ctx: Guarded,{path_args}
    if_match: IfMatch = None,
    idempotency_key: IdempotencyKey = None,
) -> Accepted:
    """{summary}.

    Returns 202. Nothing blocks an HTTP request on work that takes minutes
    (AC-B9); the caller gets a run identifier and watches the event stream.
    """
    key = require_idempotency_key(idempotency_key)
    payload = {{{payload_entries}**body.model_dump(mode="json")}}

    # A replay returns what the first request returned, rather than acting
    # twice (AC-B1). This is before any work, because a replay must not do any.
    replayed = replay_or_reserve(key, ctx, payload)
    if replayed is not None and replayed.body:
        return Accepted.model_validate(replayed.body)

    try:
        require("{tag}", {{"id": {subject_expression}}}, if_match)
    except ConcurrencyError as error:
        # The reservation is released, or the key is burnt on a request that
        # never acted and the caller can never retry it.
        release(key, ctx)
        raise as_problem(error) from error

    run_id = new_id()
    with telemetry.span("{tag}.{function}", telemetry.EDGE, runId=str(run_id)):
        telemetry.log("{tag}.accepted", runId=str(run_id))

    result = accepted(run_id, detail="{summary}")
    complete(key, ctx, status=status.HTTP_202_ACCEPTED, body=result)
    return Accepted.model_validate(result)
'''

IMPORTS: Final[dict[str, str]] = {
    "collection": (
        "from fastapi import APIRouter\n"
        "from pydantic import Field\n"
        "\n"
        "from draupnir.api import telemetry\n"
        "from draupnir.api.deps import Cursor, Guarded, PageSize, Reading\n"
        "from draupnir.api.guards import needs\n"
        "from draupnir.api.schemas import PageMeta, Wire\n"
        "from draupnir.svalinn.roles import Permission\n"
    ),
    "item": (
        "from fastapi import APIRouter\n"
        "from pydantic import Field\n"
        "\n"
        "from draupnir.api.deps import Guarded, Reading\n"
        "from draupnir.api.guards import needs\n"
        "from draupnir.api.problems import ProblemError\n"
        "from draupnir.api.schemas import Wire\n"
        "from draupnir.svalinn.roles import Permission\n"
    ),
    "mutation": (
        "from fastapi import APIRouter, status\n"
        "from pydantic import Field\n"
        "\n"
        "from draupnir.api import telemetry\n"
        "from draupnir.api.concurrency import ConcurrencyError, require\n"
        "from draupnir.api.deps import (\n"
        "    Guarded,\n"
        "    IdempotencyKey,\n"
        "    IfMatch,\n"
        "    accepted,\n"
        "    as_problem,\n"
        "    complete,\n"
        "    release,\n"
        "    replay_or_reserve,\n"
        "    require_idempotency_key,\n"
        ")\n"
        "from draupnir.api.guards import needs\n"
        "from draupnir.api.schemas import Accepted, Wire\n"
        "from draupnir.core.domain.identifiers import new_id\n"
        "from draupnir.svalinn.roles import Permission\n"
    ),
}

#: Path parameters are annotated where they are declared, so the OpenAPI
#: document describes them and the generated clients type them.
PATH_ANNOTATION = '    {name}: Annotated[str, Path(description="The {readable}.")],\n'

TEST_TEMPLATE = '''\
"""The surface checks for `{operation_id}`.

Generated by `skills/draupnir-endpoint`. It runs the same gate the API surface
contract runs -- the real guard, the real problem handlers, the real OpenAPI
document -- rather than asserting on the handler's internals.
"""

from __future__ import annotations

from typing import Any

import pytest
from fastapi import APIRouter, FastAPI
from fastapi.testclient import TestClient

from draupnir.api.app import DEFAULT_RESPONSES, bind_context
from draupnir.api.guards import enforce_declarations
from draupnir.api.problems import EXCEPTION_HANDLERS
from draupnir.api.routers import {module}

pytestmark = pytest.mark.contract


def build() -> FastAPI:
    """The router on its own application, assembled the way `create_app` does."""
    app = FastAPI(exception_handlers=EXCEPTION_HANDLERS, responses=DEFAULT_RESPONSES)
    app.middleware("http")(bind_context)
    versioned = APIRouter(prefix="/v1")
    versioned.include_router({module}.router)
    app.include_router(versioned)
    enforce_declarations(app)
    return app


def client(claims: dict[str, Any] | None = None) -> TestClient:
    """A client whose requests arrive with `claims` already verified."""
    app = build()

    @app.middleware("http")
    async def _principal(request: Any, call_next: Any) -> Any:
        request.state.claims = claims
        return await call_next(request)

    return TestClient(app, raise_server_exceptions=False)


def test_the_route_declares_a_role_and_therefore_registers() -> None:
    """AC-B6. `enforce_declarations` raises before a socket is opened."""
    assert build() is not None


def test_an_unauthenticated_request_is_refused() -> None:
    """AC-S4. The guard runs before the handler."""
    response = client().{verb}("{concrete_path}")

    assert response.status_code == 401
    assert response.headers["content-type"].startswith("application/problem+json")


def test_the_operation_is_generated_into_both_clients() -> None:
    """AC-N10: an operation id, and a typed error path."""
    document = build().openapi()
    operation = document["paths"]["/v1{path}"]["{verb}"]

    assert operation["operationId"] == "{operation_id}"
    assert "default" in operation["responses"]
    # The roles come from the same attribute the guard reads, so the published
    # permissions table cannot drift from what is enforced.
    assert "Requires:" in operation["description"]
    assert "`{role}`" in operation["description"]
{extra_tests}'''

MUTATION_TESTS = '''

def test_a_mutation_without_an_idempotency_key_is_refused() -> None:
    """AC-B1, SAD 11E.2. The retry that duplicated something omitted the header."""
    response = client({{"sub": "someone", "roles": ["{role}"], "amr": ["hwk"]}}).post(
        "{concrete_path}", json={{"reason": "because"}}
    )

    assert response.status_code == 428
    assert response.json()["code"] == "idempotency-key-required"
'''

COLLECTION_TESTS = '''

def test_the_page_is_cursor_shaped() -> None:
    """AC-B3. There is no offset parameter to reach for."""
    document = build().openapi()
    parameters = document["paths"]["/v1{path}"]["get"].get("parameters", [])
    names = {{parameter["name"] for parameter in parameters}}

    assert "cursor" in names
    assert "offset" not in names
'''


def _path_arguments(path: str) -> tuple[str, str, str, str]:
    """Return (signature lines, `del` suffix, subject expression, detail placeholder)."""
    names = PATH_PARAM.findall(path)
    if not names:
        return "", "", '"singleton"', "the collection"
    lines = "".join(
        PATH_ANNOTATION.format(name=name, readable=name.replace("_", " ")) for name in names
    )
    first = names[0]
    # The detail is substituted into an f-string in the template, so it stays a
    # placeholder rather than becoming one: `str.format` does not re-scan what
    # it substituted, which is what lets a `{name}` survive into the output.
    return "\n" + lines.rstrip("\n"), ", " + ", ".join(names), first, "{" + first + "}"


def _concrete(path: str) -> str:
    """`/corpora/{iso3}/retention` -> `/v1/corpora/GBR/retention`, for a request."""
    return "/v1" + PATH_PARAM.sub("sample", path)


#: Which role satisfies each permission, from SAD 9.4's grant table. The
#: generated test needs one to send, and picking it from the table rather than
#: guessing is why the test asserts something.
ROLE_FOR: Final[dict[str, str]] = {
    "READ": "viewer",
    "REGISTER_SOURCE": "curator",
    "CURATE": "curator",
    "SUBMIT_RUN": "operator",
    "CANCEL_RUN": "operator",
    "DECIDE_GATE": "approver",
    "PUBLISH_RELEASE": "approver",
    "MANAGE_USERS": "admin",
    "MANAGE_PLUGINS": "admin",
    "MANAGE_POLICY": "admin",
}


def _register(app_py: Path, module: str) -> bool:
    """Add the router to `create_app`, in the order the file already uses."""
    text = app_py.read_text(encoding="utf-8")
    line = f"    v1.include_router({module}.router)\n"
    if line in text:
        return False

    anchor = "    app.include_router(v1)\n"
    if anchor not in text:
        msg = (
            "draupnir/api/app.py has no `app.include_router(v1)` line to insert before. "
            "Register the router by hand, or pass --no-register."
        )
        raise ScaffoldError(msg)
    text = text.replace(anchor, line + anchor, 1)

    imported = "from draupnir.api.routers import (\n"
    if imported in text:
        start = text.index(imported) + len(imported)
        end = text.index(")\n", start)
        names = sorted({*[item.strip().rstrip(",") for item in text[start:end].split()], module})
        text = text[:start] + "".join(f"    {name},\n" for name in names) + text[end:]
    else:
        msg = (
            "draupnir/api/app.py does not import its routers as a parenthesised group, "
            "so this scaffold cannot add to it. Add the import by hand."
        )
        raise ScaffoldError(msg)

    app_py.write_text(text, encoding="utf-8", newline="\n")
    return True


def scaffold(
    *,
    router: str,
    shape: str,
    path: str,
    operation_id: str,
    summary: str,
    permission: str,
    model: str | None = None,
    tag: str | None = None,
    out: Path,
    tests_out: Path,
    app_py: Path | None = None,
) -> list[Path]:
    """Write the router and its surface checks, returning every path written."""
    if shape not in SHAPES:
        msg = f"{shape!r} is not a shape. One of: {', '.join(SHAPES)}."
        raise ScaffoldError(msg)
    if not MODULE.match(router):
        msg = f"{router!r} is not a module name. Lowercase, underscores, e.g. `retention`."
        raise ScaffoldError(msg)
    if not OPERATION_ID.match(operation_id):
        msg = (
            f"{operation_id!r} is not an operation id. It is lowerCamelCase, because it "
            "becomes the generated CLI command's name and the TypeScript operation's "
            "key, e.g. `listRetention`."
        )
        raise ScaffoldError(msg)
    if not PATH.match(path):
        msg = (
            f"{path!r} is not a path. Leading slash, lowercase segments, `{{name}}` for a "
            "parameter, and no `/v1` prefix -- `create_app` mounts every router under it."
        )
        raise ScaffoldError(msg)
    if path.startswith(("/v1/", "/v1")) and path.split("/")[1] == "v1":
        msg = (
            f"{path!r} carries the version. `create_app` mounts every router under one "
            '`APIRouter(prefix="/v1")`, so a router that adds its own answers '
            "`/v1/v1/...` and the generated clients call a path that does not exist."
        )
        raise ScaffoldError(msg)
    if permission not in PERMISSIONS:
        msg = f"{permission!r} is not a permission. SAD 9.4 names ten: {', '.join(PERMISSIONS)}."
        raise ScaffoldError(msg)
    if shape == "item" and not PATH_PARAM.search(path):
        msg = (
            "an `item` shape reads one resource, so its path needs a parameter, e.g. "
            "`/retention/{corpus_id}`. Use `collection` for a list."
        )
        raise ScaffoldError(msg)

    model = model or "".join(part.capitalize() for part in router.split("_"))
    tag = tag or router.replace("_", "-")
    function = snake(operation_id)
    role = ROLE_FOR[permission]
    path_args, path_deletes, subject, detail = _path_arguments(path)
    imports = IMPORTS[shape]
    if path_args:
        imports = "from typing import Annotated\n\n" + imports.replace(
            "from fastapi import APIRouter", "from fastapi import APIRouter, Path"
        )

    body = HEADER.format(summary=summary, imports=imports, tag=tag)
    if shape == "collection":
        body += MODELS_COLLECTION.format(model=model)
        body += COLLECTION.format(
            path=path,
            summary=summary,
            operation_id=operation_id,
            model=model,
            permission=permission,
            function=function,
            tag=tag,
            path_args=path_args,
            path_deletes=path_deletes,
            read_note=READ_NOTE,
        )
        extra_tests = COLLECTION_TESTS.format(path=path)
        verb = "get"
    elif shape == "item":
        body += MODELS_ITEM.format(model=model)
        body += ITEM.format(
            path=path,
            summary=summary,
            operation_id=operation_id,
            model=model,
            permission=permission,
            function=function,
            tag=tag,
            code=tag,
            path_args=path_args,
            detail_expression=detail,
            read_note=READ_NOTE,
        )
        extra_tests = ""
        verb = "get"
    else:
        body += MODELS_MUTATION.format(model=model)
        names = PATH_PARAM.findall(path)
        body += MUTATION.format(
            path=path,
            summary=summary,
            operation_id=operation_id,
            model=model,
            permission=permission,
            function=function,
            tag=tag,
            path_args=path_args,
            payload_entries="".join(f'"{name}": {name}, ' for name in names),
            subject_expression=subject,
        )
        extra_tests = MUTATION_TESTS.format(role=role, concrete_path=_concrete(path))
        verb = "post"

    out.mkdir(parents=True, exist_ok=True)
    tests_out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def write(target: Path, text: str) -> None:
        target.write_text(text, encoding="utf-8", newline="\n")
        written.append(target)

    write(out / f"{router}.py", body)
    write(
        tests_out / f"test_{router}_endpoint.py",
        TEST_TEMPLATE.format(
            operation_id=operation_id,
            module=router,
            path=path,
            concrete_path=_concrete(path),
            verb=verb,
            role=role,
            extra_tests=extra_tests,
        ),
    )

    if app_py is not None and _register(app_py, router):
        written.append(app_py)

    return written


def main(argv: list[str] | None = None) -> int:
    """Scaffold an operation from the command line."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--router", required=True, help="module name, e.g. retention")
    parser.add_argument("--shape", required=True, choices=SHAPES)
    parser.add_argument("--path", required=True, help="e.g. /retention/{corpus_id}, no /v1")
    parser.add_argument("--operation-id", required=True, help="lowerCamelCase, e.g. listRetention")
    parser.add_argument("--summary", required=True)
    parser.add_argument("--permission", required=True, choices=PERMISSIONS)
    parser.add_argument("--model", help="wire model prefix; defaults from --router")
    parser.add_argument("--tag", help="OpenAPI tag; defaults from --router")
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "draupnir" / "api" / "routers")
    parser.add_argument("--tests-out", type=Path, default=REPO_ROOT / "tests" / "contract")
    parser.add_argument(
        "--no-register",
        action="store_false",
        dest="register",
        help="do not add the router to create_app (for scaffolding outside the repo)",
    )
    args = parser.parse_args(argv)

    try:
        written = scaffold(
            router=args.router,
            shape=args.shape,
            path=args.path,
            operation_id=args.operation_id,
            summary=args.summary,
            permission=args.permission,
            model=args.model,
            tag=args.tag,
            out=args.out,
            tests_out=args.tests_out,
            app_py=(REPO_ROOT / "draupnir" / "api" / "app.py") if args.register else None,
        )
    except ScaffoldError as error:
        parser.error(str(error))

    for path in written:
        print(f"wrote {path}")

    if args.shape != "mutation":
        # The read the handler needs, spelled out. It is not generated, because
        # `ReadModel` is a Protocol with two implementations and a scaffold that
        # edited all three would be editing the one file where a mistake is a
        # site-scoping mistake.
        model = args.model or "".join(part.capitalize() for part in args.router.split("_"))
        returns = f"{model}Page" if args.shape == "collection" else f"{model}Out"
        extra = ", limit: int, cursor: str | None" if args.shape == "collection" else ""
        signature = f"    async def {snake(args.operation_id)}(self, site_id: str{extra})"
        print(
            "\nAdd this to the `ReadModel` Protocol in draupnir/api/reading.py, and to "
            "both `EmptyReadModel` and `DatabaseReadModel`:\n\n"
            f"{signature} -> {returns}: ...\n"
            "\nRead through `_scoped()`. Row-level security shows zero rows to a session "
            "that has not set draupnir.site_id (AC-B10, AC-F18)."
        )

    print("\nNext: `make openapi && make clients && make test-contract`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
