"""Add a RAUN evaluation suite: a jurisdiction's own gates, versioned.

The output registers, resolves alongside `general-core`, and is refused a
second time under a different definition. `tests/contract/test_skills.py` runs
this scaffold against a copy of `draupnir/raun/suites.py`, imports the result
and resolves the new suite from it -- which is the test of whether this skill
is real.

SAD 10.2 calls a jurisdiction suite a configuration change. In this build it is
a small reviewed change to one file, and that is deliberate: a suite loaded
from a file on the appliance is a suite that can differ between sites, and a
gate result whose suite definition is not in the repository is a gate result
nobody can explain two years later.
"""

from __future__ import annotations

import argparse
import re
import textwrap
from pathlib import Path
from typing import Final

REPO_ROOT = Path(__file__).resolve().parents[3]
SUITES = REPO_ROOT / "draupnir" / "raun" / "suites.py"
TESTS = REPO_ROOT / "tests" / "unit"

#: What a suite may claim to evaluate. `EVALUABLE_KINDS` in
#: `draupnir.core.domain.evidence`; a suite claiming anything else raises at
#: construction, which is a good place for it and a slow way to find out.
EVALUABLE_KINDS: Final = ("substrate", "adapter", "merged", "quantised")

#: The gates of SAD 6.2. A suite feeds gate identifiers, never thresholds --
#: a threshold here would be a threshold in two places, and GLEIPNIR owns the
#: one that decides (Decision S4).
GATES: Final = ("E1", "E2", "E3", "E4", "E5", "E6")

NAME = re.compile(r"^[a-z][a-z0-9-]*$")
#: A calendar version, as `general-core/2026.01` uses. A suite is immutable
#: once results exist against it, so the version is the thing that changes.
VERSION = re.compile(r"^\d{4}\.\d{2}$")
ISO3 = re.compile(r"^[A-Z]{3}$")


class SuiteScaffoldError(ValueError):
    """The arguments would produce a suite that cannot be registered."""


def constant_of(name: str) -> str:
    """`cim-gbr` -> `CIM_GBR`."""
    return name.upper().replace("-", "_")


DEFINITION = """
{rationale}
{constant} = Suite(
    name="{name}",
    version="{version}",
    applies_to=frozenset({{{applies_to}}}),
    gates=({gates}),
    jurisdiction={jurisdiction},
    tasks=({tasks}),
)
"""

TEST = '''\
"""The {name} evaluation suite.

Generated by `skills/raun-suite`. It checks what a suite has to be true of
rather than what it happens to contain: that it resolves for the artefact kinds
it claims, that it arrives alongside the general suite rather than instead of
it, and that it cannot be redefined under the same version.
"""

from __future__ import annotations

import pytest

from draupnir.raun import suites

pytestmark = pytest.mark.unit


def test_it_resolves_alongside_the_general_suite() -> None:
    """SAD 6.2's example names `general-core` and a jurisdiction suite together.

    Both, in that order. A jurisdiction suite that replaced the general one
    would let a model that regressed on general capability release because
    nobody measured it.
    """
    resolved = suites.default_registry().resolve("{kind}", {jurisdiction})

    assert [suite.name for suite in resolved] == ["general-core", "{name}"]


def test_it_does_not_resolve_for_another_jurisdiction() -> None:
    """A jurisdiction suite is specific, or it is not a jurisdiction suite."""
    resolved = suites.default_registry().resolve("{kind}", "ZZZ")

    assert [suite.name for suite in resolved] == ["general-core"]


def test_its_version_is_recorded_on_every_result() -> None:
    """A gate result is only explicable alongside the suite that produced it."""
    assert suites.{constant}.key == "{name}/{version}"


def test_it_cannot_be_redefined_under_the_same_version() -> None:
    """Changing a task set under a fixed version rewrites history silently.

    Every stored `gate_result` would keep its numbers and change its meaning.
    So a redefinition is refused and a new version is the only way forward.
    """
    registry = suites.default_registry()
    amended = suites.Suite(
        name="{name}",
        version="{version}",
        applies_to=suites.{constant}.applies_to,
        gates=("E1",),
        jurisdiction=suites.{constant}.jurisdiction,
    )

    with pytest.raises(suites.SuiteError, match="already registered"):
        registry.register(amended)
'''


def scaffold(
    *,
    name: str,
    version: str,
    jurisdiction: str | None,
    applies_to: tuple[str, ...],
    gates: tuple[str, ...],
    tasks: tuple[str, ...],
    rationale: str,
    suites: Path = SUITES,
    tests: Path | None = TESTS,
) -> list[Path]:
    """Define the suite, register it in `default_registry`, and test it."""
    if not NAME.match(name):
        msg = f"{name!r} is not a suite name. Lowercase with hyphens, e.g. `cim-gbr`."
        raise SuiteScaffoldError(msg)
    if not VERSION.match(version):
        msg = (
            f"{version!r} is not a suite version. Calendar versioned as `YYYY.MM`, like "
            "`general-core/2026.01`: a suite is immutable once results exist against it, "
            "so the version is what changes and the date is what it means."
        )
        raise SuiteScaffoldError(msg)
    if jurisdiction is not None and not ISO3.match(jurisdiction):
        msg = f"{jurisdiction!r} is not an ISO 3166-1 alpha-3 code, e.g. `GBR`."
        raise SuiteScaffoldError(msg)
    unknown = sorted(set(applies_to) - set(EVALUABLE_KINDS))
    if unknown:
        msg = (
            f"a suite cannot evaluate {', '.join(unknown)}. Evaluable kinds: "
            f"{', '.join(EVALUABLE_KINDS)}."
        )
        raise SuiteScaffoldError(msg)
    if not applies_to:
        msg = "a suite that applies to nothing is never resolved."
        raise SuiteScaffoldError(msg)
    unknown_gates = sorted(set(gates) - set(GATES))
    if unknown_gates:
        msg = (
            f"no gate is defined for {', '.join(unknown_gates)}. The suite of SAD 6.2 is "
            f"{', '.join(GATES)}; a new gate is a GLEIPNIR change, not a suite change."
        )
        raise SuiteScaffoldError(msg)
    if not gates:
        msg = "a suite that feeds no gates decides nothing when it runs."
        raise SuiteScaffoldError(msg)

    constant = constant_of(name)
    source = suites.read_text(encoding="utf-8")
    if f"\n{constant} = Suite(" in source:
        msg = (
            f"{constant} is already defined in {suites.name}. A suite is immutable once "
            "results exist against it: issue a new version rather than editing this one."
        )
        raise SuiteScaffoldError(msg)

    # Wrapped to the ruff line length, because a scaffold whose output has to be
    # reflowed by hand is a scaffold that has not finished.
    comment = "\n" + textwrap.fill(
        rationale, width=100, initial_indent="#: ", subsequent_indent="#: "
    )
    definition = DEFINITION.format(
        rationale=comment,
        constant=constant,
        name=name,
        version=version,
        applies_to=", ".join(f'"{kind}"' for kind in applies_to),
        gates=", ".join(f'"{gate}"' for gate in gates) + ("," if len(gates) == 1 else ""),
        jurisdiction=f'"{jurisdiction}"' if jurisdiction else "None",
        tasks=", ".join(f'"{task}"' for task in tasks) + ("," if len(tasks) == 1 else ""),
    )

    # After the general suite, so the file reads general-then-specific in the
    # order `resolve` returns them.
    anchor = "\n\n@dataclass\nclass SuiteRegistry:"
    if anchor not in source:
        msg = f"{suites} has no `SuiteRegistry` class to insert before."
        raise SuiteScaffoldError(msg)
    source = source.replace(anchor, definition.rstrip("\n") + "\n" + anchor, 1)

    registration = "    registry.register(GENERAL)\n"
    if registration not in source:
        msg = f"{suites} has no `registry.register(GENERAL)` line in `default_registry`."
        raise SuiteScaffoldError(msg)
    source = source.replace(registration, registration + f"    registry.register({constant})\n", 1)

    # `default_registry` says it holds the general suite "and nothing else",
    # which stops being true the moment this runs. A docstring that lies is
    # worse than no docstring: it is read and believed.
    source = source.replace(
        '"""A registry holding the general suite and nothing else."""',
        '"""A registry holding the general suite and every jurisdiction suite."""',
        1,
    )

    suites.write_text(source, encoding="utf-8", newline="\n")
    written = [suites]

    if tests is not None:
        tests.mkdir(parents=True, exist_ok=True)
        target = tests / f"test_{constant.lower()}_suite.py"
        target.write_text(
            TEST.format(
                name=name,
                version=version,
                constant=constant,
                kind=applies_to[0],
                jurisdiction=f'"{jurisdiction}"' if jurisdiction else "None",
            ),
            encoding="utf-8",
            newline="\n",
        )
        written.append(target)

    return written


def main(argv: list[str] | None = None) -> int:
    """Scaffold a suite from the command line."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="e.g. cim-gbr")
    parser.add_argument("--version", required=True, help="YYYY.MM, e.g. 2026.01")
    parser.add_argument("--jurisdiction", help="ISO 3166-1 alpha-3, e.g. GBR")
    parser.add_argument(
        "--applies-to", nargs="+", default=list(EVALUABLE_KINDS), choices=EVALUABLE_KINDS
    )
    parser.add_argument("--gate", action="append", dest="gates", choices=GATES)
    parser.add_argument("--task", action="append", dest="tasks", default=[])
    parser.add_argument("--rationale", required=True, help="why this suite exists, in one line")
    parser.add_argument("--suites", type=Path, default=SUITES)
    parser.add_argument("--tests", type=Path, default=TESTS)
    args = parser.parse_args(argv)

    try:
        written = scaffold(
            name=args.name,
            version=args.version,
            jurisdiction=args.jurisdiction,
            applies_to=tuple(args.applies_to),
            gates=tuple(args.gates or GATES),
            tasks=tuple(args.tasks),
            rationale=args.rationale,
            suites=args.suites,
            tests=args.tests,
        )
    except SuiteScaffoldError as error:
        parser.error(str(error))

    for path in written:
        print(f"wrote {path}")
    print(
        "\nNext: capture a baseline for it (`draupnir.raun.baselines`) -- a relative "
        "gate with no baseline is refused, not passed -- then `make test-unit`."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
