"""Scaffold a JARNGREIPR component: seven states, tokens only, named by role.

The output passes the token linter, `stories.test.ts` and an axe run in jsdom
with no manual edit. That is the test of whether this skill is real, and
`tests/contract/test_skills.py` regenerates the worked example and compares it
byte for byte with what is committed.

Three things are generated rather than described, because all three are what a
component author gets wrong under time pressure: the seven state stories, the
`StateSurface` delegation, and a stylesheet that reaches for a hex value only
by never having one in it.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Final

REPO_ROOT = Path(__file__).resolve().parents[3]
SRC = REPO_ROOT / "web" / "packages" / "jarngreipr" / "src"

#: `primitives` are the sixteen generic controls, `composites` the eight
#: DRAUPNIR-shaped assemblies, and `example` is where this skill's worked
#: example lives -- inside the package so the token linter, `tsc`, Storybook
#: and Vitest all see it, and out of `index.ts` so it is not public API.
LAYERS: Final = ("primitives", "composites", "example")

NAME = re.compile(r"^[A-Z][A-Za-z0-9]*$")

#: The seven story exports Storybook's static indexer will find, in story
#: order. `stories.test.ts` asserts exactly this list.
STORY_EXPORTS: Final = (
    "Ready",
    "Loading",
    "Empty",
    "ErrorState",
    "Denied",
    "ReadOnly",
    "Partitioned",
)


class ComponentError(ValueError):
    """The arguments would produce a component that cannot pass the gates."""


def kebab(name: str) -> str:
    """`PoolStatus` -> `pool-status`, for the CSS class prefix."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


COMPONENT = """\
import type {{ JSX }} from 'react';
import {{ StateSurface, type StateProps }} from '{states}';
import './{name}.css';

/** One row of {summary_lower} */
export interface {name}Item {{
  /** Stable identifier. Used as the React key, so it must not be an index. */
  id: string;
  /** What this row is called, in the operator's words rather than the schema's. */
  label: string;
  /**
   * The value, already formatted. Formatting here would mean a locale decision
   * inside a design system, and the caller is the one that knows the locale.
   */
  value: string;
  /**
   * How the value reads. Carried as a word as well as a colour, because a
   * status that is only a colour is a status a third of readers cannot see
   * (WCAG 1.4.1).
   */
  tone?: 'neutral' | 'info' | 'success' | 'warning' | 'danger' | undefined;
}}

export interface {name}Props extends StateProps {{
  /** What this component is, for its accessible name. */
  label: string;
  /** The rows. An empty array is not the `empty` state -- the caller says so. */
  items: {name}Item[];
}}

/**
 * {summary}
 *
 * Generated by `skills/jarngreipr-component`.
 *
 * The five replacing states are delegated to `StateSurface` rather than
 * implemented here. That is the whole reason the state layer sits under the
 * components: a component that renders its own "no permission" panel renders a
 * slightly different one, and by the twentieth component `denied` means five
 * things. Here it means one.
 *
 * `readOnly` is not delegated, because it does not replace the content: the
 * rows stay visible and the controls go inert, so the shape of what exists is
 * still legible to someone who cannot change it.
 */
export function {name}({{
  label,
  items,
  state = 'ready',
  stateMessage,
  problem,
}}: {name}Props): JSX.Element {{
  const inert = state === 'readOnly';

  return (
    <div className="jg-{slug}" data-jg-state={{state}}>
      <StateSurface
        state={{state}}
        stateMessage={{stateMessage}}
        problem={{problem}}
        label={{label}}
        minHeight="6rem"
      >
        <h3 className="jg-{slug}__label">{{label}}</h3>
        <ul className="jg-{slug}__list" aria-label={{label}}>
          {{items.map((item) => (
            <li className="jg-{slug}__row" key={{item.id}} data-jg-tone={{item.tone ?? 'neutral'}}>
              <span className="jg-{slug}__name">{{item.label}}</span>
              <span className="jg-{slug}__value">{{item.value}}</span>
            </li>
          ))}}
        </ul>
        {{inert ? (
          <p className="jg-{slug}__note">Read only. You may see this and not change it.</p>
        ) : null}}
      </StateSurface>
    </div>
  );
}}
"""

STYLES = """\
/* {name}. Generated by `skills/jarngreipr-component`.
 *
 * Every value here is a token. AC-U3: tokens are the only source of visual
 * values, and `scripts/token-lint.mjs` fails the build on a literal colour,
 * spacing or radius. The rule is enforced rather than documented because a
 * design system whose only defence is a guideline drifts within a release.
 *
 * Intrinsic sizing is deliberately not tokenised -- a row is one line of text
 * tall because that is what one line occupies, not because anyone chose it. */

.jg-{slug} {{
  display: flex;
  flex-direction: column;
  gap: var(--jg-space-2);
}}

.jg-{slug}__label {{
  margin: var(--jg-space-0);
  font-size: var(--jg-text-sm);
  font-weight: var(--jg-weight-semibold);
  color: var(--jg-text);
}}

.jg-{slug}__list {{
  margin: var(--jg-space-0);
  padding: var(--jg-space-0);
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: var(--jg-space-1);
}}

.jg-{slug}__row {{
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: var(--jg-space-3);
  padding: var(--jg-space-1) var(--jg-space-2);
  background: var(--jg-surface-sunken);
  border: var(--jg-border-width) solid var(--jg-border-subtle);
  border-radius: var(--jg-radius-sm);
}}

.jg-{slug}__row[data-jg-tone='info'] {{
  border-color: var(--jg-info-border);
}}

.jg-{slug}__row[data-jg-tone='success'] {{
  border-color: var(--jg-success-border);
}}

.jg-{slug}__row[data-jg-tone='warning'] {{
  border-color: var(--jg-warning-border);
}}

.jg-{slug}__row[data-jg-tone='danger'] {{
  border-color: var(--jg-danger-border);
}}

.jg-{slug}__name {{
  font-size: var(--jg-text-sm);
  color: var(--jg-text);
}}

.jg-{slug}__value {{
  font-family: var(--jg-font-mono);
  font-size: var(--jg-text-sm);
  font-variant-numeric: tabular-nums;
  color: var(--jg-text-muted);
}}

.jg-{slug}__note {{
  margin: var(--jg-space-0);
  font-size: var(--jg-text-xs);
  color: var(--jg-text-muted);
}}
"""

STORIES = """\
import type {{ Meta }} from '@storybook/react';
import {{ COMPONENT_META, SAMPLE_PROBLEM, stateStories }} from '{stories_module}';
import {{ {name} }} from './{name}';

// A literal, because Storybook's story indexer is static: a default export it
// cannot read at parse time is a component that never appears in the sidebar.
export default {{
  title: '{title}/{name}',
  ...COMPONENT_META,
}} satisfies Meta;

const SAMPLE = [
  {{ id: 'adapters', label: 'adapters', value: '18 / 24', tone: 'warning' }},
  {{ id: 'merges', label: 'merges', value: '2 / 8', tone: 'success' }},
  {{ id: 'export', label: 'export', value: '0 / 4', tone: 'neutral' }},
] as const;

const stories = stateStories((state) => (
  <{name} label="{label}" items={{[...SAMPLE]}} state={{state}} problem={{SAMPLE_PROBLEM}} />
));

{exports}"""


def _relative(layer: str) -> tuple[str, str, str]:
    """Return the import paths and the Storybook title for `layer`."""
    return "../state/states", "../state/stories", layer.capitalize()


def scaffold(
    *,
    name: str,
    layer: str,
    summary: str,
    src: Path = SRC,
    label: str | None = None,
) -> list[Path]:
    """Write the component, its stylesheet and its stories."""
    if not NAME.match(name):
        msg = (
            f"{name!r} is not a component name. PascalCase, e.g. `PoolStatus`: it is "
            "the exported symbol, the story file's stem and the Storybook title."
        )
        raise ComponentError(msg)
    if layer not in LAYERS:
        msg = f"{layer!r} is not a layer. One of: {', '.join(LAYERS)}."
        raise ComponentError(msg)
    if not summary.endswith("."):
        msg = "the summary is the component's docstring first line; end it with a full stop."
        raise ComponentError(msg)

    states, stories_module, title = _relative(layer)
    slug = kebab(name)
    directory = src / layer
    directory.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def write(target: Path, text: str) -> None:
        target.write_text(text, encoding="utf-8", newline="\n")
        written.append(target)

    write(
        directory / f"{name}.tsx",
        COMPONENT.format(
            name=name,
            slug=slug,
            states=states,
            summary=summary,
            summary_lower=summary[0].lower() + summary[1:],
        ),
    )
    write(directory / f"{name}.css", STYLES.format(name=name, slug=slug))
    write(
        directory / f"{name}.stories.tsx",
        STORIES.format(
            name=name,
            stories_module=stories_module,
            title=title,
            label=label or summary.rstrip("."),
            exports="\n".join(
                f"export const {export} = stories.{export};" for export in STORY_EXPORTS
            )
            + "\n",
        ),
    )

    if layer != "example":
        written.extend(_register(src, layer, name))

    return written


def _register(src: Path, layer: str, name: str) -> list[Path]:
    """Export the component from its layer barrel and from the package barrel.

    `stories.test.ts` reads `index.ts`'s `export { ... } from './<layer>'`
    block to decide which components must have seven stories. A component
    missing from it ships whatever stories it happens to have, and nothing
    fails -- which is the hole this closes.
    """
    changed: list[Path] = []

    barrel = src / layer / "index.tsx"
    text = barrel.read_text(encoding="utf-8")
    line = f"export * from './{name}';\n"
    if line not in text:
        text = text.rstrip("\n") + "\n\n" + line
        barrel.write_text(text, encoding="utf-8", newline="\n")
        changed.append(barrel)

    package = src / "index.ts"
    source = package.read_text(encoding="utf-8")
    updated = _insert_export(source, layer, name, values=True)
    updated = _insert_export(updated, layer, f"{name}Props", values=False)
    if updated != source:
        package.write_text(updated, encoding="utf-8", newline="\n")
        changed.append(package)

    return changed


def _insert_export(source: str, layer: str, symbol: str, *, values: bool) -> str:
    """Add `symbol` to the sorted export block for `layer`, if not already there."""
    keyword = "export {" if values else "export type {"
    pattern = re.compile(
        rf"{re.escape(keyword)}\n(?P<body>(?:^  .*\n)+)}} from '\./{layer}';",
        re.MULTILINE,
    )
    match = pattern.search(source)
    if match is None:
        kind = "value" if values else "type"
        msg = (
            f"web/packages/jarngreipr/src/index.ts has no sorted {kind} export block for "
            f"./{layer}. Add the export by hand."
        )
        raise ComponentError(msg)

    entries = [line.strip().rstrip(",") for line in match.group("body").splitlines()]
    if symbol in entries:
        return source
    merged = sorted([*entries, symbol])
    body = "".join(f"  {entry},\n" for entry in merged)
    return source[: match.start("body")] + body + source[match.end("body") :]


def main(argv: list[str] | None = None) -> int:
    """Scaffold a component from the command line."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="PascalCase, e.g. PoolStatus")
    parser.add_argument("--layer", required=True, choices=LAYERS)
    parser.add_argument("--summary", required=True, help="the docstring's first line")
    parser.add_argument("--label", help="the story's accessible name; defaults to the summary")
    parser.add_argument("--src", type=Path, default=SRC)
    args = parser.parse_args(argv)

    try:
        written = scaffold(
            name=args.name,
            layer=args.layer,
            summary=args.summary,
            src=args.src,
            label=args.label,
        )
    except ComponentError as error:
        parser.error(str(error))

    for path in written:
        print(f"wrote {path}")
    print(
        "\nNext: `pnpm lint:tokens`, `pnpm test` and `pnpm --filter @draupnir/jarngreipr "
        "typecheck`. Then write the component's actual content in place of the rows."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
