import { readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { workspaceRoot } from './source';

/**
 * The committed baselines, checked for completeness per platform. RF-22.
 *
 * Every baseline in this repository is `…-win32.png` and the pipeline runs on
 * `ubuntu-24.04-arm`, so stage 2.9 compared nothing on every run it ever made.
 * The missing half is generated by the `visual-baselines` workflow and
 * committed by a person; what this asserts is the property that has to hold
 * afterwards and cannot be checked by the workflow that produces them.
 *
 * **Every platform carries the same set of stories.** Not "some baselines
 * exist" — a platform with 219 of 220 is the failure that matters, because the
 * one story without a baseline is silently ungated while the stage stays
 * green, which is RF-22 again in miniature. Comparing platforms against each
 * other rather than against `index.json` is deliberate: the index needs a
 * built Storybook, which is gitignored, so a check that read it would only run
 * where somebody had already built one.
 */

const SNAPSHOTS = join(workspaceRoot(), 'e2e', 'visual', 'storybook.spec.ts-snapshots');

/** Story ids that have a baseline, grouped by platform. */
function byPlatform(): Map<string, Set<string>> {
  const found = new Map<string, Set<string>>();
  for (const file of readdirSync(SNAPSHOTS)) {
    const match = /^(?<story>.+)-visual-(?<platform>[a-z0-9]+)\.png$/.exec(file);
    if (!match?.groups) {
      continue;
    }
    const { story, platform } = match.groups;
    if (!story || !platform) {
      continue;
    }
    const stories = found.get(platform) ?? new Set<string>();
    stories.add(story);
    found.set(platform, stories);
  }
  return found;
}

describe('the committed visual baselines', () => {
  it('exist at all', () => {
    // The gate has two operands and this is the one held in the repository.
    expect(byPlatform().size).toBeGreaterThan(0);
  });

  it('cover the same stories on every platform that has any', () => {
    const platforms = byPlatform();
    const names = [...platforms.keys()].sort();
    const reference = names[0] ?? '';
    const others = names.slice(1);
    const expected = platforms.get(reference) ?? new Set<string>();

    for (const platform of others) {
      const stories = platforms.get(platform) ?? new Set<string>();
      const missing = [...expected].filter((story) => !stories.has(story)).sort();
      const extra = [...stories].filter((story) => !expected.has(story)).sort();

      expect(missing, `${platform} has no baseline for these, but ${reference} does`).toEqual([]);
      expect(extra, `${platform} has baselines ${reference} does not`).toEqual([]);
    }
  });

  it('names each file so the platform is readable in a diff', () => {
    // `…-visual-linux.png`. A reviewer looking at a pull request that touches
    // baselines has to be able to see which platform's evidence moved.
    const files = readdirSync(SNAPSHOTS).filter((file) => file.endsWith('.png'));
    const unnamed = files.filter((file) => !/-visual-[a-z0-9]+\.png$/.test(file));

    expect(unnamed).toEqual([]);
  });
});
