"""Policy and roles: the two tables that decide, published as they are enforced.

`GET /v1/policy` and `GET /v1/roles`.

Both endpoints exist because a control nobody can read is a control nobody can
check. Article 53 requires the copyright policy to be machine readable and
published (SAD 9A), and SAD 9.4 makes the role table part of the compliance
evidence pack -- but the deeper reason is the one Decision S4 draws: GLEIPNIR
judges and HODD records. A judgement whose rule cannot be shown afterwards is
indistinguishable from an opinion.

Neither is a copy. `/v1/policy` renders the same `Policy` object the licence
gate decides with, and `/v1/roles` renders the same declarations `@needs`
enforces. There is nothing here that could drift from what actually happens,
because there is nothing here that is written twice.
"""

from __future__ import annotations

from fastapi import APIRouter, Request

from draupnir.api import telemetry
from draupnir.api.deps import Guarded
from draupnir.api.guards import needs, permissions_table
from draupnir.api.schemas import (
    PolicyBundleOut,
    PolicyOut,
    PolicyRuleOut,
    RoleOut,
    RolesOut,
    RoutePermissionOut,
)
from draupnir.gleipnir import licence
from draupnir.gleipnir.policy import Policy
from draupnir.svalinn import roles as role_table
from draupnir.svalinn.roles import Permission

router = APIRouter(tags=["operations"])


def _bundle(policy: Policy) -> PolicyBundleOut:
    """Render a policy as the console shows it."""
    return PolicyBundleOut(
        version=policy.version,
        rules=[
            PolicyRuleOut(
                id=rule.id,
                statement=rule.statement,
                verdict=str(rule.verdict),
                licences=sorted(rule.licences),
                personal_data=rule.personal_data,
                attribution_required=rule.attribution_required,
            )
            for rule in policy.rules
        ],
        default_verdict=str(policy.default),
        default_statement=policy.default_statement,
    )


@router.get(
    "/policy",
    summary="The licence policy in force, and the one before it",
    operation_id="getPolicy",
    response_model=PolicyOut,
)
@needs(Permission.READ)
async def get_policy(ctx: Guarded) -> PolicyOut:
    """The current bundle and its predecessor.

    Both, because a policy version on its own tells an operator what the rules
    are and not what changed. The screen renders the difference, and a
    difference needs two sides.
    """
    del ctx
    telemetry.log("policy.read", version=licence.CURRENT.version)
    return PolicyOut(current=_bundle(licence.CURRENT), previous=_bundle(licence.PREVIOUS))


@router.get(
    "/roles",
    summary="Roles, their permissions, and what each route requires",
    operation_id="getRoles",
    response_model=RolesOut,
)
@needs(Permission.READ)
async def get_roles(request: Request, ctx: Guarded) -> RolesOut:
    """The role table and the route table, from the enforced declarations.

    The route half is generated by walking the registered routes and reading
    the same `@needs` declaration the guard reads at request time. A published
    table assembled by hand would be a second statement of the rule, and the
    two would disagree the first time somebody added an endpoint.
    """
    del ctx
    granted = role_table.as_payload()
    rows = permissions_table(request.app)

    telemetry.log("roles.read", roles=len(granted), routes=len(rows))
    return RolesOut(
        roles=[
            RoleOut(role=name, permissions=permissions) for name, permissions in granted.items()
        ],
        routes=[
            RoutePermissionOut(
                method=", ".join(str(item) for item in row.get("methods", [])),
                path=str(row.get("path", "")),
                permission=(str(row["permission"]) if row.get("permission") is not None else None),
                reason=(str(row["reason"]) if row.get("reason") is not None else None),
            )
            for row in rows
        ],
        separation=(
            "No role both submits and approves (Decision S6). An operator submits runs and "
            "cannot sign a release; an approver signs releases and cannot submit the run "
            "being signed for. A person holding both roles would be able to approve their "
            "own work, which is the concentration SAD 16A exists to prevent."
        ),
    )
