import type { JSX } from 'react';
import { StateSurface, type StateProps } from '../state/states';
import './PoolStatus.css';

/** One row of allocation pools and how much of each is in use. */
export interface PoolStatusItem {
  /** Stable identifier. Used as the React key, so it must not be an index. */
  id: string;
  /** What this row is called, in the operator's words rather than the schema's. */
  label: string;
  /**
   * The value, already formatted. Formatting here would mean a locale decision
   * inside a design system, and the caller is the one that knows the locale.
   */
  value: string;
  /**
   * How the value reads. Carried as a word as well as a colour, because a
   * status that is only a colour is a status a third of readers cannot see
   * (WCAG 1.4.1).
   */
  tone?: 'neutral' | 'info' | 'success' | 'warning' | 'danger' | undefined;
}

export interface PoolStatusProps extends StateProps {
  /** What this component is, for its accessible name. */
  label: string;
  /** The rows. An empty array is not the `empty` state -- the caller says so. */
  items: PoolStatusItem[];
}

/**
 * Allocation pools and how much of each is in use.
 *
 * Generated by `skills/jarngreipr-component`.
 *
 * The five replacing states are delegated to `StateSurface` rather than
 * implemented here. That is the whole reason the state layer sits under the
 * components: a component that renders its own "no permission" panel renders a
 * slightly different one, and by the twentieth component `denied` means five
 * things. Here it means one.
 *
 * `readOnly` is not delegated, because it does not replace the content: the
 * rows stay visible and the controls go inert, so the shape of what exists is
 * still legible to someone who cannot change it.
 */
export function PoolStatus({
  label,
  items,
  state = 'ready',
  stateMessage,
  problem,
}: PoolStatusProps): JSX.Element {
  const inert = state === 'readOnly';

  return (
    <div className="jg-pool-status" data-jg-state={state}>
      <StateSurface
        state={state}
        stateMessage={stateMessage}
        problem={problem}
        label={label}
        minHeight="6rem"
      >
        <h3 className="jg-pool-status__label">{label}</h3>
        <ul className="jg-pool-status__list" aria-label={label}>
          {items.map((item) => (
            <li className="jg-pool-status__row" key={item.id} data-jg-tone={item.tone ?? 'neutral'}>
              <span className="jg-pool-status__name">{item.label}</span>
              <span className="jg-pool-status__value">{item.value}</span>
            </li>
          ))}
        </ul>
        {inert ? (
          <p className="jg-pool-status__note">Read only. You may see this and not change it.</p>
        ) : null}
      </StateSurface>
    </div>
  );
}
