"""Generate a README for every module package, from its package docstring.

AC-D1: "Every module has a README stating its responsibility and its explicit
non responsibilities, matching section 5.2."

Generated rather than authored, for the same reason the clients are: two
statements of one responsibility drift, and the one that drifts is the one
nobody runs. The package docstring is what a developer reads at the top of the
file they are editing, so that is the copy that is true, and this renders it
where a reader looking at the directory listing will find it.

`tests/unit/test_module_readmes.py` regenerates and compares, so a docstring
that changes without its README fails the build.
"""

from __future__ import annotations

import argparse
import ast
import re
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "draupnir"

#: The two statements AC-D1 asks for, spelled as SAD 5.2 spells them.
OWNS = "Owns:"
MUST_NOT = "Must not:"

HEADER = """<!--
Generated by `scripts/module_readmes.py` from the package docstring in
`{module}/__init__.py`. Edit the docstring, then run `make module-readmes`.
A README edited by hand is a second statement of one responsibility, and the
second one is always the one that goes stale.
-->

# `draupnir.{name}`

"""


class ReadmeError(Exception):
    """Raised when a package cannot produce the README AC-D1 requires."""


def packages(root: Path = PACKAGE) -> list[Path]:
    """Every package directly under `draupnir/`, in name order.

    Directly under, not recursively: SAD 5.2's table is about the modules, and
    a README beside every submodule would be an index nobody reads.
    """
    return sorted(
        path for path in root.iterdir() if path.is_dir() and (path / "__init__.py").is_file()
    )


def docstring_of(package: Path) -> str:
    """The package docstring, parsed rather than imported.

    Parsing keeps this runnable before the package is installed, and keeps a
    documentation generator from executing the code it documents.
    """
    source = (package / "__init__.py").read_text(encoding="utf-8")
    text = ast.get_docstring(ast.parse(source), clean=True)
    if not text:
        msg = f"{package.name} has no package docstring; AC-D1 has nothing to render"
        raise ReadmeError(msg)
    return text


def render(package: Path) -> str:
    """The README for one package."""
    text = docstring_of(package)
    for required in (OWNS, MUST_NOT):
        if required not in text:
            msg = (
                f"{package.name}'s docstring does not state `{required}`. AC-D1 asks for "
                "the responsibility and the explicit non responsibilities, and SAD 5.2 "
                "states both for every module."
            )
            raise ReadmeError(msg)

    body = _emphasise(text)
    relative = package.relative_to(ROOT).as_posix()
    return HEADER.format(module=relative, name=package.name) + body.rstrip("\n") + "\n"


def _emphasise(text: str) -> str:
    """Render the two AC-D1 statements as their own paragraphs.

    They are the answer to the question the criterion asks, and a reader
    skimming a directory of READMEs should find them without reading the prose
    around them.
    """
    lines = text.splitlines()
    out: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if line.startswith((OWNS, MUST_NOT)):
            label, _, rest = line.partition(":")
            block = [rest.strip()]
            index += 1
            while (
                index < len(lines)
                and lines[index]
                and not lines[index].startswith((OWNS, MUST_NOT, "|", "    "))
            ):
                block.append(lines[index].strip())
                index += 1
            paragraph = " ".join(part for part in block if part)
            out.extend(["", f"**{label}.** {paragraph}", ""])
            continue
        out.append(line)
        index += 1

    rendered = textwrap.dedent("\n".join(out)).strip("\n")
    # One blank line between paragraphs. Two say nothing more than one.
    return re.sub(r"\n{3,}", "\n\n", rendered) + "\n"


def write(root: Path = PACKAGE) -> list[Path]:
    """Write every README, returning the paths written."""
    written: list[Path] = []
    for package in packages(root):
        target = package / "README.md"
        target.write_text(render(package), encoding="utf-8", newline="\n")
        written.append(target)
    return written


def main(argv: list[str] | None = None) -> int:
    """Write the READMEs, or check that they are current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any README is stale")
    args = parser.parse_args(argv)

    stale: list[str] = []
    for package in packages():
        target = package / "README.md"
        expected = render(package)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            if current != expected:
                stale.append(package.name)
            continue
        target.write_text(expected, encoding="utf-8", newline="\n")
        print(f"wrote {target.relative_to(ROOT)}")

    if args.check:
        if stale:
            print(f"stale README(s): {', '.join(stale)}. Run `make module-readmes`.")
            return 1
        print(f"{len(packages())} module README(s) current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
