"""Scaffold a conforming DRAUPNIR plug-in driver.

The output passes `check_job_driver` with no manual edit. That is the test of
whether this skill is real, and `tests/contract/test_skills.py` runs it.

Everything the generated driver does is a consequence of one rule: `render` is
pure (SAD Decision S5). It is why there is no `os`, no `datetime`, no network
client and no file write anywhere in the rendered plan, and why the capability
set is declared once and consulted by `validate` rather than restated.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Final

REPO_ROOT = Path(__file__).resolve().parents[3]

#: The seven extension points of SAD 8.2, and the Protocol each takes.
GROUPS: Final[dict[str, str]] = {
    "draupnir.train": "TrainDriver",
    "draupnir.merge": "MergeDriver",
    "draupnir.eval": "EvalDriver",
    "draupnir.export": "ExportDriver",
    "draupnir.schedule": "ScheduleDriver",
    "draupnir.store": "StoreDriver",
    "draupnir.policy": "PolicyDriver",
}

#: The groups whose drivers plan and collect a job, and which `check_job_driver`
#: therefore covers. The other three have narrower interfaces of their own.
JOB_GROUPS: Final = frozenset(
    {"draupnir.train", "draupnir.merge", "draupnir.eval", "draupnir.export"}
)

#: `artefact_kind` in the database. A driver that invents a ninth value writes
#: a row the schema refuses, and it refuses it at collection time -- after the
#: allocation has been spent.
ARTEFACT_KINDS: Final = (
    "corpus_raw",
    "corpus_curated",
    "base_model",
    "substrate",
    "adapter",
    "merged",
    "quantised",
    "report",
)

#: `namespace.implementation/vMAJOR`, the same shape `InterfaceName` parses.
#: Checked here so a mistyped name is a scaffold error rather than a
#: conformance finding an hour later.
NAME_PATTERN: Final = re.compile(r"^[a-z0-9_]+\.[a-z0-9_]+/v[1-9][0-9]*$")

DISTRIBUTION_PATTERN: Final = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)+$")


class ScaffoldError(ValueError):
    """The arguments would produce a driver that cannot conform."""


def module_of(distribution: str) -> str:
    """`veldris-draupnir-zip-export` -> `draupnir_zip_export`."""
    return distribution.removeprefix("veldris-").replace("-", "_")


def class_of(name: str) -> str:
    """`skidbladnir.zip/v1` -> `ZipDriver`."""
    local = name.split("/", 1)[0].split(".")[-1]
    return "".join(part.capitalize() for part in local.split("_")) + "Driver"


DRIVER_TEMPLATE = '''\
"""{summary}

Generated by `skills/draupnir-driver`. Two methods carry this driver's own
logic -- `validate` and `render` -- and the rest is the shape every driver in
this group shares.

`render` is pure, as SAD Decision S5 requires: it returns a command built from
the specification and nothing else. It opens no file, resolves no name and
takes no clock reading, because a plan that depends on any of those cannot be
reproduced from the specification that asked for it. The conformance suite
checks that by rendering twice, rendering again after a pause, rendering with
the network removed, and comparing the working directory before and after.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path

from draupnir.interfaces.types import (
    JobPlan,
    ProducedArtefact,
    ProgressEvent,
    ProgressKind,
    ResourceRequest,
    RunArtefacts,
    RunSpec,
    ValidationError,
)

NAME = "{name}"

#: The extension point this driver is loaded for. Named here so `validate` asks
#: the specification what *this* group requires, rather than reaching into
#: whichever block happens to hold it today.
GROUP = "{group}"

#: What this driver declares it can do. SAD 10.3 rule 4: the core refuses to
#: plan a job whose specification requires a capability not declared here, and
#: the refusal names the demand. Declared once, so `validate` consults it
#: rather than restating it.
CAPABILITIES = frozenset({{{capabilities}}})

#: What the job is expected to leave behind. Named here rather than inline so
#: `render` and `collect` cannot drift apart about it.
OUTPUT = "{output}"

#: The `artefact_kind` the output is recorded as. One of the eight the schema
#: knows; a ninth is refused at collection time, after the allocation is spent.
OUTPUT_KIND = "{artefact_kind}"

#: `step 10/100`, optionally followed by `loss=1.234`.
_STEP = re.compile(r"^step\\s+(?P<step>\\d+)\\s*/\\s*(?P<total>\\d+)")
_LOSS = re.compile(r"\\bloss\\s*=\\s*(?P<loss>-?\\d+(?:\\.\\d+)?)")


@dataclass
class {classname}:
    """{summary}"""

    name: str = NAME
    capabilities: frozenset[str] = CAPABILITIES
    #: Keeps the dataclass keyword-constructible without a mutable default
    #: leaking onto the class. The loader constructs a driver with no arguments.
    _: dict[str, str] = field(default_factory=dict, repr=False)

    # -- plan ---------------------------------------------------------------

    def validate(self, spec: RunSpec) -> list[ValidationError]:
        """Return every reason this driver cannot run `spec`.

        Returns rather than raises, and returns *all* of the problems: an
        operator correcting a specification needs one round trip, not five.
        """
        problems: list[ValidationError] = []

        unsupported = sorted(spec.capabilities_for(GROUP) - self.capabilities)
        if unsupported:
            declared = ", ".join(sorted(self.capabilities))
            problems.append(
                ValidationError(
                    field="spec",
                    message=(
                        f"{{NAME}} declares {{declared}}, and this specification "
                        f"requires {{', '.join(unsupported)}}"
                    ),
                    code="unsupported-capability",
                )
            )

        # Your own checks go here. Append to `problems`; never raise, and never
        # return early on the first one.

        return problems

    def render(self, spec: RunSpec, workdir: Path) -> JobPlan:
        """Return the exact command this job runs.

        Pure. Everything it uses comes from `spec`. `workdir` is where the job
        will run and is deliberately not read: reading it would make the plan a
        function of the machine that rendered it.
        """
        del workdir

        return JobPlan(
            command=(
                "{executable}",
                "--run",
                spec.metadata.name,
                "--base",
                spec.base.artefact,
                "--output",
                OUTPUT,
            ),
            environment={{"PYTHONHASHSEED": "0"}},
            workdir=".",
            resources=ResourceRequest(
                partition=spec.placement.partition,
                nodes=spec.placement.nodes,
                gpus_per_node={gpus},
            ),
            expected_artefacts=(OUTPUT,),
        )

    # -- observe ------------------------------------------------------------

    def parse_progress(self, line: str) -> ProgressEvent | None:
        """Translate one line of tool output into an event, or return None.

        Total and pure: any line at all, twice, the same answer, and `None` for
        a line that carries no event. It stamps no time, so replaying a
        captured log yields the events it yielded live.
        """
        match = _STEP.match(line.strip())
        if match is None:
            return None
        loss = _LOSS.search(line)
        return ProgressEvent(
            kind=ProgressKind.LOSS if loss else ProgressKind.STEP,
            step=int(match["step"]),
            total=int(match["total"]),
            value=float(loss["loss"]) if loss else None,
        )

    # -- collect ------------------------------------------------------------

    def collect(self, workdir: Path) -> RunArtefacts:
        """Return what the job produced, with digests. Reads; never writes."""
        produced = workdir / OUTPUT
        if not produced.is_file():
            # Absence is a finding for the caller, not a silence and not an
            # exception: the run is what failed, and collection is what says so.
            return RunArtefacts()

        return RunArtefacts(
            artefacts=(
                ProducedArtefact(
                    path=OUTPUT,
                    kind=OUTPUT_KIND,
                    sha256=_digest(produced),
                    size=produced.stat().st_size,
                ),
            )
        )


def _digest(path: Path, *, block: int = 1 << 20) -> str:
    """SHA-256 of a file, read in blocks so a large artefact never loads."""
    running = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(block), b""):
            running.update(chunk)
    return running.hexdigest()


#: What the entry point resolves to. The loader constructs nothing: it reads
#: this object, checks it against the Protocol and registers it.
driver = {classname}()

__all__ = ["CAPABILITIES", "NAME", "OUTPUT", "{classname}", "driver"]
'''

PYPROJECT_TEMPLATE = """\
# Generated by `skills/draupnir-driver`.
#
# AC-N9: a driver is admitted by entry point discovery alone. Nothing under
# `draupnir/` changes to accept this distribution, and the import linter's
# driver contract holds that as a rule rather than as a happy result.

[project]
name = "{distribution}"
version = "0.1.0"
description = "{summary}"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = {{ text = "Proprietary" }}
dependencies = ["veldris-draupnir"]

# The control plane is a workspace sibling in development and a released
# distribution afterwards. This declaration is what makes both work.
[tool.uv.sources]
veldris-draupnir = {{ workspace = true }}

[project.entry-points."{group}"]
"{name}" = "{module}:driver"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# The wheel is what the signing manifest covers. An unsigned distribution does
# not load (AC-S7); `DRAUPNIR_DEV=1` is the only way past that, and it names
# itself in the log on every start that uses it.
[tool.hatch.build.targets.wheel]
packages = ["{module}"]
"""

README_TEMPLATE = """\
# {distribution}

{summary}

Generated by `skills/draupnir-driver`. It implements `{protocol}` for the
`{group}` extension point and declares the capabilities {capability_list}.

## What it refuses

A specification requiring a capability it has not declared. The refusal names
the demand, so an operator can see where it came from (SAD 10.3 rule 4).

## What it deliberately does not do

`render` is pure (Decision S5). It reads nothing, writes nothing and takes no
clock reading, so two renders of one specification are byte-identical and a
recorded plan can be re-derived years later.

## Conformance

```bash
uv sync
uv run pytest {test_path} -q
```

That runs the published harness, the same suite a third party runs against
their own driver.
"""

TEST_TEMPLATE = '''\
"""The conformance run for {distribution}.

Generated by `skills/draupnir-driver`. It runs the published harness rather
than asserting on the driver's internals: a driver is conforming when the suite
everyone else runs says it is.
"""

from __future__ import annotations

from pathlib import Path

import pytest

{testing_import}from {module} import driver

pytestmark = pytest.mark.contract
{constants}

def test_the_driver_conforms(tmp_path: Path) -> None:
    """Every check in the published suite, against the installed driver."""
    findings = check_job_driver(driver, sample_spec({accepted_call}), tmp_path)
    assert findings == [], describe(findings)
{refusal_test}'''

CONSTANTS_TEMPLATE = """
#: The `{block}` block of the SAD 6.2 sample. It asks for more than a freshly
#: scaffolded driver declares, so the conformance run narrows it to what this
#: driver actually offers rather than watching it refuse the example.
SAMPLE = SAMPLE_SPEC_MAPPING["spec"]["{block}"]
ACCEPTED = {{**SAMPLE, {accepted}}}
REFUSED = {{**SAMPLE, {refused}}}
"""

REFUSAL_TEST_TEMPLATE = '''

def test_it_refuses_a_capability_it_has_not_declared() -> None:
    """SAD 10.3 rule 4, and the refusal names the demand."""
    problems = driver.validate(sample_spec({block}=REFUSED))
    assert [problem.code for problem in problems] == ["unsupported-capability"]
    assert "{undeclared}" in problems[0].message
'''

#: The `spec` block each group's capabilities are read off, and the key within
#: it that carries them. The SAD 6.2 sample asks for three export formats, two
#: eval suites and LoRA at bf16, so a freshly scaffolded driver would otherwise
#: fail its own conformance run on the first line -- correct behaviour, and a
#: useless first experience.
_BLOCKS: Final[dict[str, tuple[str, str]]] = {
    "draupnir.export": ("release", "formats"),
    "draupnir.eval": ("evaluate", "suites"),
    "draupnir.train": ("train", "method"),
}

#: `capabilities_for("draupnir.train")` puts the specification's precision in
#: the demand alongside its method, so a train driver that declares no
#: precision can never be selected. These are the names the estate uses.
PRECISIONS: Final = frozenset({"bf16", "fp16", "fp32", "fp8", "int8", "nf4"})

UNDECLARED: Final = "no_such_capability"


def _overrides(group: str, capabilities: tuple[str, ...]) -> tuple[str, str, str]:
    """Return (block name, accepted block, refused block) for the generated test.

    A merge driver reads no capability off the specification, so the sample
    runs unmodified and there is nothing here for it to refuse.
    """
    if group not in _BLOCKS:
        return "", "", ""
    block, key = _BLOCKS[group]
    if group == "draupnir.train":
        precisions = [item for item in capabilities if item in PRECISIONS]
        methods = [item for item in capabilities if item not in PRECISIONS]
        if not precisions or not methods:
            msg = (
                "a train driver's demand is its method and its precision together "
                "(`RunSpec.capabilities_for`), so declare at least one of each, e.g. "
                "`--capability lora --capability bf16`. Known precisions: "
                f"{', '.join(sorted(PRECISIONS))}."
            )
            raise ScaffoldError(msg)
        precision = json.dumps(precisions[0])
        return (
            block,
            f'"{key}": {json.dumps(methods[0])}, "precision": {precision}',
            f'"{key}": {json.dumps(UNDECLARED)}, "precision": {precision}',
        )
    return (
        block,
        f'"{key}": {json.dumps(list(capabilities))}',
        f'"{key}": {json.dumps([UNDECLARED])}',
    )


def _insert_sorted(text: str, pattern: re.Pattern[str], line: str) -> str:
    """Insert `line` into the block `pattern` matches, preserving its order.

    Idempotent: a line already present is left where it is. A block that is
    already alphabetical stays alphabetical, and one that is in some deliberate
    order of its own -- the import contract lists its drivers roughly in the
    order they were built -- is appended to rather than rearranged. A scaffold
    that reorders a file it was asked to add one line to produces a diff nobody
    can review.
    """
    match = pattern.search(text)
    if match is None:
        msg = (
            "the root pyproject.toml has no block matching "
            f"{pattern.pattern!r}. Register the distribution by hand, or pass "
            "--no-register."
        )
        raise ScaffoldError(msg)
    body = match.group("body")
    existing = [entry for entry in body.splitlines() if entry.strip()]
    if any(entry.strip() == line.strip() for entry in existing):
        return text
    indent = existing[0][: len(existing[0]) - len(existing[0].lstrip())] if existing else ""
    entry = indent + line.strip()
    keys = [item.strip() for item in existing]
    merged = (
        sorted([*existing, entry], key=str.strip) if keys == sorted(keys) else [*existing, entry]
    )
    return text[: match.start("body")] + "\n".join(merged) + "\n" + text[match.end("body") :]


#: `[tool.uv.sources]` at the root, which is where a workspace member is
#: declared, and the isort first-party list, which is what makes the generated
#: conformance test's import land in the right block.
_UV_SOURCES = re.compile(
    r"(?m)^\[tool\.uv\.sources\]\n(?P<body>(?:^[a-z0-9-]+ = .*\n)+)", re.MULTILINE
)
_FIRST_PARTY = re.compile(r"(?m)^known-first-party = \[\n(?P<body>(?:^  \".*\",\n)+)\]")


#: The packages import-linter analyses, and the `source_modules` of the
#: contract that forbids a driver from importing the core. Both name every
#: driver rather than matching a pattern, so a driver missing from either is a
#: driver the contract does not check -- and nothing fails while it is missing,
#: which is what makes this worth automating.
_ROOT_PACKAGES = re.compile(r"(?m)^root_packages =\n(?P<body>(?:^ +\S+\n)+)")
_DRIVER_CONTRACT = re.compile(
    r"(?ms)^\[importlinter:contract:drivers-depend-on-interfaces-only\].*?"
    r"^source_modules =\n(?P<body>(?:^ +\S+\n)+)"
)


def register(pyproject: Path, importlinter: Path, distribution: str, module: str) -> list[Path]:
    """Declare the new driver where the toolchain has to be told about it.

    Four entries, all four of which every existing driver already has: the
    workspace source, so `uv sync` installs it; the isort first-party name, so
    the generated conformance test's import sorts where it belongs; and
    import-linter's `root_packages` and driver contract `source_modules`,
    because that contract lists its drivers by name.

    The first two are why the output lints without a manual edit, which is the
    claim this skill makes. The last two are the ones a person forgets, and
    forgetting them fails nothing: the contract quietly stops covering the
    newest driver, which is the shape of failure AC-N9 exists to prevent.
    """
    changed: list[Path] = []

    text = pyproject.read_text(encoding="utf-8")
    updated = _insert_sorted(text, _UV_SOURCES, f"{distribution} = {{ workspace = true }}")
    updated = _insert_sorted(updated, _FIRST_PARTY, f'"{module}",')
    if updated != text:
        pyproject.write_text(updated, encoding="utf-8", newline="\n")
        changed.append(pyproject)

    contracts = importlinter.read_text(encoding="utf-8")
    amended = _insert_sorted(contracts, _ROOT_PACKAGES, module)
    amended = _insert_sorted(amended, _DRIVER_CONTRACT, module)
    if amended != contracts:
        importlinter.write_text(amended, encoding="utf-8", newline="\n")
        changed.append(importlinter)

    return changed


def scaffold(
    *,
    group: str,
    name: str,
    distribution: str,
    capabilities: tuple[str, ...],
    out: Path,
    tests_out: Path,
    pyproject: Path | None = None,
    summary: str | None = None,
    executable: str | None = None,
    output: str = "output.bin",
    artefact_kind: str = "report",
    gpus: int = 0,
) -> list[Path]:
    """Write the distribution and its conformance run, returning every path."""
    if group not in GROUPS:
        msg = f"{group} is not an extension point. One of: {', '.join(sorted(GROUPS))}"
        raise ScaffoldError(msg)
    if group not in JOB_GROUPS:
        msg = (
            f"a {group} driver plans no job, so this scaffold does not fit it. It "
            "generates the shape `check_job_driver` checks, which covers "
            f"{', '.join(sorted(JOB_GROUPS))}."
        )
        raise ScaffoldError(msg)
    if not NAME_PATTERN.match(name):
        msg = (
            f"{name!r} is not a versioned interface name. The form is "
            "`namespace.implementation/vMAJOR`, e.g. `skidbladnir.zip/v1`: the major "
            "version lives in the name so two majors can be installed at once "
            "(SAD 10.3 rule 1)."
        )
        raise ScaffoldError(msg)
    if not DISTRIBUTION_PATTERN.match(distribution):
        msg = (
            f"{distribution!r} is not a distribution name. Use lowercase words joined "
            "by hyphens, e.g. `veldris-draupnir-zip-export`."
        )
        raise ScaffoldError(msg)
    if not capabilities:
        msg = (
            "a driver declares at least one capability. One that declares none can "
            "never be selected, because selection is by capability (SAD 10.3 rule 4)."
        )
        raise ScaffoldError(msg)
    if artefact_kind not in ARTEFACT_KINDS:
        msg = (
            f"{artefact_kind!r} is not an artefact kind. The schema knows "
            f"{', '.join(ARTEFACT_KINDS)}, and refuses a ninth at collection time."
        )
        raise ScaffoldError(msg)

    module = module_of(distribution)
    classname = class_of(name)
    protocol = GROUPS[group]
    summary = summary or f"{protocol} for DRAUPNIR: {', '.join(capabilities)}."
    executable = executable or module.replace("_", "-")
    block, accepted, refused = _overrides(group, capabilities)
    constants = (
        CONSTANTS_TEMPLATE.format(block=block, accepted=accepted, refused=refused) if block else ""
    )
    testing_import = (
        "from draupnir.interfaces.testing import (\n"
        "    SAMPLE_SPEC_MAPPING,\n"
        "    check_job_driver,\n"
        "    describe,\n"
        "    sample_spec,\n"
        ")\n"
        if block
        else "from draupnir.interfaces.testing import check_job_driver, describe, sample_spec\n"
    )
    accepted_call = f"{block}=ACCEPTED" if block else ""
    refusal_test = REFUSAL_TEST_TEMPLATE.format(block=block, undeclared=UNDECLARED) if block else ""

    test_path = tests_out / f"test_{module}.py"
    package = out / module
    package.mkdir(parents=True, exist_ok=True)
    tests_out.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def write(path: Path, text: str) -> None:
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)

    write(
        package / "__init__.py",
        DRIVER_TEMPLATE.format(
            summary=summary,
            name=name,
            group=group,
            capabilities=", ".join(f'"{item}"' for item in capabilities),
            classname=classname,
            executable=executable,
            output=output,
            artefact_kind=artefact_kind,
            gpus=gpus,
        ),
    )
    write(
        out / "pyproject.toml",
        PYPROJECT_TEMPLATE.format(
            distribution=distribution,
            summary=summary,
            group=group,
            name=name,
            module=module,
        ),
    )
    write(
        out / "README.md",
        README_TEMPLATE.format(
            distribution=distribution,
            summary=summary,
            protocol=protocol,
            group=group,
            capability_list=", ".join(f"`{item}`" for item in capabilities),
            test_path=test_path.as_posix(),
        ),
    )
    write(
        test_path,
        TEST_TEMPLATE.format(
            distribution=distribution,
            module=module,
            testing_import=testing_import,
            constants=constants,
            accepted_call=accepted_call,
            refusal_test=refusal_test,
        ),
    )

    if pyproject is not None:
        written.extend(
            register(pyproject, pyproject.parent / ".importlinter", distribution, module)
        )

    return written


def main(argv: list[str] | None = None) -> int:
    """Scaffold a driver from the command line."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--group", required=True, choices=sorted(GROUPS))
    parser.add_argument("--name", required=True, help="e.g. skidbladnir.zip/v1")
    parser.add_argument("--distribution", required=True, help="e.g. veldris-draupnir-zip-export")
    parser.add_argument(
        "--capability", action="append", required=True, dest="capabilities", metavar="CAP"
    )
    parser.add_argument("--out", type=Path, required=True, help="e.g. plugins/zip_export")
    parser.add_argument("--tests-out", type=Path, default=REPO_ROOT / "tests" / "contract")
    parser.add_argument(
        "--no-register",
        action="store_false",
        dest="register",
        help="do not touch the root pyproject.toml (for scaffolding outside the repo)",
    )
    parser.add_argument("--summary")
    parser.add_argument("--executable", help="defaults to the module name, hyphenated")
    parser.add_argument("--output", default="output.bin")
    parser.add_argument("--artefact-kind", default="report", choices=ARTEFACT_KINDS)
    parser.add_argument("--gpus", type=int, default=0)
    args = parser.parse_args(argv)

    try:
        written = scaffold(
            group=args.group,
            name=args.name,
            distribution=args.distribution,
            capabilities=tuple(args.capabilities),
            out=args.out,
            tests_out=args.tests_out,
            pyproject=(REPO_ROOT / "pyproject.toml") if args.register else None,
            summary=args.summary,
            executable=args.executable,
            output=args.output,
            artefact_kind=args.artefact_kind,
            gpus=args.gpus,
        )
    except ScaffoldError as error:
        parser.error(str(error))

    for path in written:
        print(f"wrote {path}")
    print("\nNext: `uv sync`, then `uv run pytest -m contract` to put it through the harness.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
