"""Generated command table. Do not edit.

Produced by `scripts/generate_cli.py` from `docs/api/openapi.json`.
The pipeline regenerates this file and fails on any diff (AC-Q2).
"""

from __future__ import annotations

from dataclasses import dataclass

GENERATED_FROM_OPENAPI_VERSION = "0.1.0"


@dataclass(frozen=True, slots=True)
class Operation:
    """One operation of the API contract, as the CLI sees it."""

    operation_id: str
    command: str
    method: str
    path: str
    summary: str
    path_params: tuple[str, ...]
    has_body: bool


OPERATIONS: tuple[Operation, ...] = (
    Operation(
        operation_id="getHealth",
        command="get-health",
        method="GET",
        path="/healthz",
        summary="Liveness",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getMetrics",
        command="get-metrics",
        method="GET",
        path="/metrics",
        summary="Prometheus metrics",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getReadiness",
        command="get-readiness",
        method="GET",
        path="/readyz",
        summary="Readiness",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getArray",
        command="get-array",
        method="GET",
        path="/v1/arrays",
        summary="The adapter array and its element states",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="listCorpora",
        command="list-corpora",
        method="GET",
        path="/v1/corpora",
        summary="Corpora by jurisdiction, with curation progress",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="curateCorpus",
        command="curate-corpus",
        method="POST",
        path="/v1/corpora/{iso3}/curate",
        summary="Run the curation pipeline",
        path_params=("iso3",),
        has_body=False,
    ),
    Operation(
        operation_id="ingestCorpus",
        command="ingest-corpus",
        method="POST",
        path="/v1/corpora/{iso3}/ingest",
        summary="Ingest and hash a jurisdiction's sources",
        path_params=("iso3",),
        has_body=False,
    ),
    Operation(
        operation_id="streamSiteEvents",
        command="stream-site-events",
        method="GET",
        path="/v1/events",
        summary="Watch this site's state deltas",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="listGates",
        command="list-gates",
        method="GET",
        path="/v1/gates",
        summary="The approval queue",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="decideGate",
        command="decide-gate",
        method="POST",
        path="/v1/gates/{gate_id}/decide",
        summary="Approve or reject",
        path_params=("gate_id",),
        has_body=True,
    ),
    Operation(
        operation_id="getLedger",
        command="get-ledger",
        method="GET",
        path="/v1/ledger",
        summary="Ledger slice with chain verification",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getLedgerEntry",
        command="get-ledger-entry",
        method="GET",
        path="/v1/ledger/{entry_hash}",
        summary="One ledger entry, with its hash recomputed",
        path_params=("entry_hash",),
        has_body=False,
    ),
    Operation(
        operation_id="getLineage",
        command="get-lineage",
        method="GET",
        path="/v1/lineage/{artefact}",
        summary="Full lineage attestation",
        path_params=("artefact",),
        has_body=False,
    ),
    Operation(
        operation_id="exportAttestation",
        command="export-attestation",
        method="GET",
        path="/v1/lineage/{artefact}/attestation",
        summary="A signed lineage bundle, for export",
        path_params=("artefact",),
        has_body=False,
    ),
    Operation(
        operation_id="listModels",
        command="list-models",
        method="GET",
        path="/v1/models",
        summary="The model registry",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getModel",
        command="get-model",
        method="GET",
        path="/v1/models/{artefact}",
        summary="One model, its artefacts and its gate results",
        path_params=("artefact",),
        has_body=False,
    ),
    Operation(
        operation_id="listPlugins",
        command="list-plugins",
        method="GET",
        path="/v1/plugins",
        summary="Installed plug-ins and signature status",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getPolicy",
        command="get-policy",
        method="GET",
        path="/v1/policy",
        summary="The licence policy in force, and the one before it",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getRelease",
        command="get-release",
        method="GET",
        path="/v1/releases/{artefact}",
        summary="The release package",
        path_params=("artefact",),
        has_body=False,
    ),
    Operation(
        operation_id="publishRelease",
        command="publish-release",
        method="POST",
        path="/v1/releases/{artefact}/publish",
        summary="Publish a release",
        path_params=("artefact",),
        has_body=False,
    ),
    Operation(
        operation_id="listRetention",
        command="list-retention",
        method="GET",
        path="/v1/retention",
        summary="Retention actions, due and executed",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="getRoles",
        command="get-roles",
        method="GET",
        path="/v1/roles",
        summary="Roles, their permissions, and what each route requires",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="listRuns",
        command="list-runs",
        method="GET",
        path="/v1/runs",
        summary="List runs",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="submitRun",
        command="submit-run",
        method="POST",
        path="/v1/runs",
        summary="Submit a run specification",
        path_params=(),
        has_body=True,
    ),
    Operation(
        operation_id="dryRunSpecification",
        command="dry-run-specification",
        method="POST",
        path="/v1/runs/dry-run",
        summary="Render a run specification without submitting it",
        path_params=(),
        has_body=True,
    ),
    Operation(
        operation_id="getRun",
        command="get-run",
        method="GET",
        path="/v1/runs/{run_id}",
        summary="Inspect a run",
        path_params=("run_id",),
        has_body=False,
    ),
    Operation(
        operation_id="cancelRun",
        command="cancel-run",
        method="POST",
        path="/v1/runs/{run_id}/cancel",
        summary="Cancel a run",
        path_params=("run_id",),
        has_body=True,
    ),
    Operation(
        operation_id="streamRunEvents",
        command="stream-run-events",
        method="GET",
        path="/v1/runs/{run_id}/events",
        summary="Watch a run's state deltas",
        path_params=("run_id",),
        has_body=False,
    ),
    Operation(
        operation_id="retryRun",
        command="retry-run",
        method="POST",
        path="/v1/runs/{run_id}/retry",
        summary="Retry a run",
        path_params=("run_id",),
        has_body=False,
    ),
    Operation(
        operation_id="search",
        command="search",
        method="GET",
        path="/v1/search",
        summary="Search runs, sources and ledger entries",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="listSites",
        command="list-sites",
        method="GET",
        path="/v1/sites",
        summary="The registered sites",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="listSources",
        command="list-sources",
        method="GET",
        path="/v1/sources",
        summary="List registered sources",
        path_params=(),
        has_body=False,
    ),
    Operation(
        operation_id="registerSource",
        command="register-source",
        method="POST",
        path="/v1/sources",
        summary="Register a corpus source",
        path_params=(),
        has_body=True,
    ),
    Operation(
        operation_id="getSweep",
        command="get-sweep",
        method="GET",
        path="/v1/sweeps/{run_id}",
        summary="A reweighting sweep, as merge points against gates",
        path_params=("run_id",),
        has_body=False,
    ),
)
